### ISSUE TITLE
用dockercompose 使用集群方式启动报错 单机没问题  docker-startup.sh脚本也加了命令

### ISSUE THREAD

**Issue by xl-0909** [wuchubuzai2018/nacos-datasource-extend-plugins#3]
```yaml
services:
  nacos:
    image: nacos/nacos-server
    container_name: nacos
    hostname: nacos
    volumes:
      - /opt/nacos/config/docker-startup.sh:/home/nacos/bin/docker-startup.sh
      - /opt/nacos/config/:/home/nacos/conf/
      - /opt/nacos/plugins/:/home/nacos/plugins/
      - /opt/nacos/logs/:/home/nacos/logs
    environment:
      PREFER_HOST_MODE: ip
      MODE: cluster
      NACOS_SERVERS: 192.168.56.104
      NACOS_SERVERS: 192.168.56.104:8848 192.168.56.105:8848 192.168.56.106:8848 
      JVM_XMS: 512m
      JVM_MMS: 320m
    network_mode: host
```

```properties
spring.sql.init.platform=${SPRING_DATASOURCE_PLATFORM:postgresql}
db.num=${MYSQL_DATABASE_NUM:1}
db.url.0=jdbc:postgresql://192.168.8.26:9001/nacos?currentSchema=public&stringtype=unspecified
db.user=${MYSQL_SERVICE_USER:xxx}
db.password=${MYSQL_SERVICE_PASSWORD:xxx}
db.pool.config.driverClassName=org.postgresql.Driver
```

启动报错[db-load-error]load jdbc.properties error
如果用单机模式启动就没可以

docker-startup.sh 增加了`JAVA_OPT="${JAVA_OPT} -Dloader.path=${BASE_DIR}/plugins,${BASE_DIR}/plugins/health,${BASE_DIR}/plugins/cmdb,${BASE_DIR}/plugins/selector"`
